quiz:
  path: /Quizzes/quiz.csv
  localeLabel: EN
  requiredScore: 3
  logType: console

spring:
  messages:
    basename: messages
    use-code-as-default-message: true
    fallback-to-system-locale: false
